# permissions for end users to edit contextsystemmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contextsystemmappings-editor-role
rules:
- apiGroups:
  - beta.example.com
  resources:
  - contextsystemmappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - beta.example.com
  resources:
  - contextsystemmappings/status
  verbs:
  - get
