# permissions for end users to edit contexts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: context-editor-role
rules:
- apiGroups:
  - beta.example.com
  resources:
  - contexts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - beta.example.com
  resources:
  - contexts/status
  verbs:
  - get
