
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - beta.example.com
  resources:
  - contexts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - beta.example.com
  resources:
  - contexts/finalizers
  verbs:
  - update
- apiGroups:
  - beta.example.com
  resources:
  - contexts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - beta.example.com
  resources:
  - contextsystemmappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - beta.example.com
  resources:
  - contextsystemmappings/finalizers
  verbs:
  - update
- apiGroups:
  - beta.example.com
  resources:
  - contextsystemmappings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - beta.example.com
  resources:
  - systems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - beta.example.com
  resources:
  - systems/finalizers
  verbs:
  - update
- apiGroups:
  - beta.example.com
  resources:
  - systems/status
  verbs:
  - get
  - patch
  - update
